create-calender
Hitoshi082508/saving-app pull request #2
Opened 2021-12-11 07:20 UTC by Hitoshi082508

カレンダーコンポーネントを作成しました！
atomic designに沿って、コンポーネントを設計していきます！
より綺麗にコードを書くにはどのようにしたらいいのか、例えば、関数を分けるなどアドバイスをいただけると幸いです・・！
特にcssの書き方を教えていただけると嬉しいです！

2021-12-14 01:40 UTC, kakukakug commented on App.tsx
> +import { Calender } from './src/components/molecules/Calendar';
いいですね！Atomicコンポーネントの概念に基づいてディレクトリ分けましたね。
今はまだカレンダーしかないですが、もっと増えた時に便利になるはずですし、再利用とかもしやすくなりますね！

2021-12-14 01:51 UTC, kakukakug requested changes

2021-12-14 01:51 UTC, kakukakug commented on src/types/index.ts
> +export type CalenderDateType = {
型の情報定義を切り出したのは良いと思います！

もしもこれが増えてくる想定であれば、index.ts ではなく、calendar.ts とかに名前を変えて置いておいた方が使いやすいかも

2021-12-14 01:51 UTC, kakukakug commented on src/components/molecules/Calendar.tsx
> +          <TouchableOpacity style={styles.container}>
dayComponent だけ切り出してcomponents/Atomとかにファイル分けるということもできますね。

2021-12-14 01:51 UTC, kakukakug commented on src/components/molecules/Calendar.tsx
> +const styles = StyleSheet.create({
style はまだ少ししかないので、特に変なとこはないですよ。
実際の画面で崩れてないのであれば良いでしょう。

2021-12-14 01:51 UTC, kakukakug commented on src/components/molecules/Calendar.tsx
> +      style={{ marginTop: 100 }}
インラインで書くのはほんの少しですがパフォーマンスに影響します。
たくさんになってきたり、繰り返し使うような場所だと影響大きくなるので、変数とかで可変でない固定の値でいい場合はなるべくStyleSheet.createでstylesに用意して設定しましょう！

2021-12-14 01:51 UTC, kakukakug commented on src/components/molecules/Calendar.tsx
> +export const Calender: React.FC<Props> = ({ className }) => {
```suggestion
export const Calender: React.FC<Props> = ({ className }) => {
```
```suggestion
export const Calendar: React.FC<Props> = ({ className }) => {
```

Calendar　じゃないだろうか。

2021-12-14 01:51 UTC, kakukakug commented on src/components/molecules/Calendar.tsx
> +import { CalenderDateType } from '../../types';
```suggestion
import { CalenderDateType } from '../../types';
```
```suggestion
import { CalendarDateType } from '../../types';
```
ここもCalendarDateTypeでは

2021-12-14 01:54 UTC, kakukakug requested changes

2021-12-14 01:54 UTC, kakukakug commented on src/components/molecules/Calendar.tsx
> +            <Text style={{textAlign: 'center', color: today === date.dateString ? '#67AEDF' : date.month === month ? '#000' : '#CCC'}}>
今月なのか、今日なのかの判定をここでしてますが、return の前でもできるはず。
Textコンポーネントの中でやるとソースコードが見にくくなってしまうので、できればreturn の前にtrue/false まで判定を行なっておければ、コンポーネント部分を見やすくできます。

2021-12-22 12:12 UTC, Hitoshi082508 commented on src/components/molecules/Calendar.tsx
> +          <TouchableOpacity style={styles.container}>
なるほど、、
そっちの方が綺麗ですね！

2021-12-22 12:13 UTC, Hitoshi082508 commented on src/components/molecules/Calendar.tsx
> +      style={{ marginTop: 100 }}
インラインで書くっていうのはコンポーネントに対して、style={{margintop: 100}}みたいな感じで直接書くってことですよね？

2021-12-22 12:14 UTC, Hitoshi082508 commented on src/components/molecules/Calendar.tsx
> +export const Calender: React.FC<Props> = ({ className }) => {
スペルミスってますねwww

2021-12-22 12:15 UTC, merged